[package]
name = "typesafe-derive-builder"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
description = "Derive builder macro"
license = "MIT"
edition = "2018"

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
rand = "0.3.18"

[lib]
proc-macro = true
